version: '3'

services:
    kucoin-monitor-server:
        build:
          context: .
          dockerfile: server/Dockerfile
        image: kucoin-monitor-server
        container_name: kucoin-monitor-server
        restart: unless-stopped
        env_file: .env
        ports:
          - "8883:8080"
        volumes:
          - .:/home/node/app
          - node_modules:/home/node/app/node_modules
        networks:
          - app-network
        command: /home/node/app/node_modules/.bin/nodemon server/server.js
    kucoin-monitor-scripts:
        build:
            context: .
            dockerfile: scripts/Dockerfile
        image: kucoin-monitor-scripts
        container_name: kucoin-monitor-scripts
        restart: unless-stopped
        env_file: .env
        ports:
          - "9000:8080"
        command: "scripts/loanMarketData.handler"

networks:
    app-network:
        driver: bridge
    
volumes:
    dbdata:
    node_modules:
