version: '3.4'

services:
  kucoin-monitor-server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]

  kucoin-monitor-scripts:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    image: kucoin-monitor-scripts
    container_name: kucoin-monitor-scripts
    restart: unless-stopped
    ports:
      - "9000:8080"
    command: "scripts/loanMarketData.handler"
