version: '3.4'

services:
  kucoin-monitor-server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: development
    env_file: .env
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./server/bin/www"]

  kucoin-monitor-scripts:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    image: kucoin-monitor-scripts
    container_name: kucoin-monitor-scripts
    restart: unless-stopped
    env_file: .env
    ports:
      - "9000:8080"
    command: "scripts/loanMarketData.handler"
